<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="StateMachine" Id="{90ec7814-8409-473f-9bb8-82d15f76498a}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK StateMachine
VAR_INPUT
END_VAR
VAR_OUTPUT
	OutputSignals : OutputSignals;
END_VAR
VAR
	i : INT;
	state : States;
	Timer : Timer;
	
	// Boolean var to start or stop the whole process.
	// If start becomes false after a cycle has started, the mechanism will finish the cycle and then it will not start a new one (cycle).
	Start: BOOL:=FALSE;
	
	TotalNumberCylindersPicked : INT:=0;
	CylinderInDisc : ARRAY[1..6] OF BOOL := [FALSE,5(TRUE)]; // Buffer array that tracks if there is a cylinder on a slot, and slides its elements when disc rotates
	Sensor: BOOL:= CylinderInDisc[GVL.SENSOR_POSITION_IN_DISC]; // Sensor is placed in front of slot 4
	// The variable PutCylinderInSlot6 simulates incoming cylinders in the disc. If a new cylinder is added, it will take the 6th slot
	PutCylinderInSlot6 : BOOL;
	
	// Some assumptions
	// The mechanism starts always from position G and always with gripper open. After a cycle of cylinder pick and place, the gripper does not close.
	// It stays open as it will be ready to pick the next cylinder.
	
	
END_VAR
]]></Declaration>
    <Implementation>
      <SFC>
        <XmlArchive>
          <Data>
            <o xml:space="preserve" t="SFCImplementationObject">
              <o n="Root" t="SFCSegment">
                <o n="ElementList" t="SFCElementList">
                  <l2 n="InnerList">
                    <o t="SFCStep">
                      <n n="EmbeddedMainAction" />
                      <n n="EmbeddedEntryAction" />
                      <n n="EmbeddedExitAction" />
                      <l2 n="EmbeddedMainActionProperties" />
                      <l2 n="EmbeddedEntryActionProperties" />
                      <l2 n="EmbeddedExitActionProperties" />
                      <o n="ElementList" t="SFCElementList">
                        <l2 n="InnerList" />
                      </o>
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"Init"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">403L</v>
                          <v n="IdParent">402L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">404L</v>
                          <v n="IdParent">402L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">405L</v>
                          <v n="IdParent">402L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">406L</v>
                          <v n="IdParent">402L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"TRUE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">407L</v>
                          <v n="IdParent">402L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">408L</v>
                          <v n="IdParent">402L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">409L</v>
                          <v n="IdParent">402L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">410L</v>
                          <v n="IdParent">402L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">411L</v>
                          <v n="IdParent">402L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"Init_entry"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">412L</v>
                          <v n="IdParent">402L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">413L</v>
                          <v n="IdParent">402L</v>
                        </o>
                      </l2>
                      <v n="Id">402L</v>
                      <v n="IdParent">9L</v>
                    </o>
                    <o t="SFCTransition">
                      <v n="VariableName">"Init__to__ROTATE_DISC"</v>
                      <n n="EmbeddedTransition" />
                      <l2 n="EmbeddedTransitionProperties" />
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"Start"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">447L</v>
                          <v n="IdParent">446L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">448L</v>
                          <v n="IdParent">446L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">449L</v>
                          <v n="IdParent">446L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">450L</v>
                          <v n="IdParent">446L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">451L</v>
                          <v n="IdParent">446L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">452L</v>
                          <v n="IdParent">446L</v>
                        </o>
                      </l2>
                      <v n="Id">446L</v>
                      <v n="IdParent">9L</v>
                    </o>
                    <o t="SFCStep">
                      <n n="EmbeddedMainAction" />
                      <n n="EmbeddedEntryAction" />
                      <n n="EmbeddedExitAction" />
                      <l2 n="EmbeddedMainActionProperties" />
                      <l2 n="EmbeddedEntryActionProperties" />
                      <l2 n="EmbeddedExitActionProperties" />
                      <o n="ElementList" t="SFCElementList">
                        <l2 n="InnerList" />
                      </o>
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"ROTATE_DISC"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">435L</v>
                          <v n="IdParent">434L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">436L</v>
                          <v n="IdParent">434L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">437L</v>
                          <v n="IdParent">434L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">438L</v>
                          <v n="IdParent">434L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">439L</v>
                          <v n="IdParent">434L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">440L</v>
                          <v n="IdParent">434L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">441L</v>
                          <v n="IdParent">434L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">442L</v>
                          <v n="IdParent">434L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"ROTATE_DISC_active"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">443L</v>
                          <v n="IdParent">434L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">444L</v>
                          <v n="IdParent">434L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">445L</v>
                          <v n="IdParent">434L</v>
                        </o>
                      </l2>
                      <v n="Id">434L</v>
                      <v n="IdParent">9L</v>
                    </o>
                    <o t="SFCTransition">
                      <v n="VariableName">"ROTATE_DISC__to__LINEAR_FW"</v>
                      <n n="EmbeddedTransition" />
                      <l2 n="EmbeddedTransitionProperties" />
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"state = States.LINEAR_FW"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">428L</v>
                          <v n="IdParent">427L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">429L</v>
                          <v n="IdParent">427L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">430L</v>
                          <v n="IdParent">427L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">431L</v>
                          <v n="IdParent">427L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">432L</v>
                          <v n="IdParent">427L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">433L</v>
                          <v n="IdParent">427L</v>
                        </o>
                      </l2>
                      <v n="Id">427L</v>
                      <v n="IdParent">9L</v>
                    </o>
                    <o t="SFCStep">
                      <n n="EmbeddedMainAction" />
                      <n n="EmbeddedEntryAction" />
                      <n n="EmbeddedExitAction" />
                      <l2 n="EmbeddedMainActionProperties" />
                      <l2 n="EmbeddedEntryActionProperties" />
                      <l2 n="EmbeddedExitActionProperties" />
                      <o n="ElementList" t="SFCElementList">
                        <l2 n="InnerList" />
                      </o>
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"LINEAR_FW"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">455L</v>
                          <v n="IdParent">454L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">456L</v>
                          <v n="IdParent">454L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">457L</v>
                          <v n="IdParent">454L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">458L</v>
                          <v n="IdParent">454L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">459L</v>
                          <v n="IdParent">454L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">460L</v>
                          <v n="IdParent">454L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">461L</v>
                          <v n="IdParent">454L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">462L</v>
                          <v n="IdParent">454L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"LINEAR_FW_active"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">463L</v>
                          <v n="IdParent">454L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">464L</v>
                          <v n="IdParent">454L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">465L</v>
                          <v n="IdParent">454L</v>
                        </o>
                      </l2>
                      <v n="Id">454L</v>
                      <v n="IdParent">9L</v>
                    </o>
                    <o t="SFCTransition">
                      <v n="VariableName">"LINEAR_FW__to__GRIPPER_LOWER"</v>
                      <n n="EmbeddedTransition" />
                      <l2 n="EmbeddedTransitionProperties" />
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"state = States.GRIPPER_LOWER"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">502L</v>
                          <v n="IdParent">501L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">503L</v>
                          <v n="IdParent">501L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">504L</v>
                          <v n="IdParent">501L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">505L</v>
                          <v n="IdParent">501L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">506L</v>
                          <v n="IdParent">501L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">507L</v>
                          <v n="IdParent">501L</v>
                        </o>
                      </l2>
                      <v n="Id">501L</v>
                      <v n="IdParent">9L</v>
                    </o>
                    <o t="SFCStep">
                      <n n="EmbeddedMainAction" />
                      <n n="EmbeddedEntryAction" />
                      <n n="EmbeddedExitAction" />
                      <l2 n="EmbeddedMainActionProperties" />
                      <l2 n="EmbeddedEntryActionProperties" />
                      <l2 n="EmbeddedExitActionProperties" />
                      <o n="ElementList" t="SFCElementList">
                        <l2 n="InnerList" />
                      </o>
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"GRIPPER_LOWER"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">490L</v>
                          <v n="IdParent">489L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">491L</v>
                          <v n="IdParent">489L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">492L</v>
                          <v n="IdParent">489L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">493L</v>
                          <v n="IdParent">489L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">494L</v>
                          <v n="IdParent">489L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">495L</v>
                          <v n="IdParent">489L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">496L</v>
                          <v n="IdParent">489L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">497L</v>
                          <v n="IdParent">489L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"GRIPPER_LOWER_active"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">498L</v>
                          <v n="IdParent">489L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">499L</v>
                          <v n="IdParent">489L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">500L</v>
                          <v n="IdParent">489L</v>
                        </o>
                      </l2>
                      <v n="Id">489L</v>
                      <v n="IdParent">9L</v>
                    </o>
                    <o t="SFCTransition">
                      <v n="VariableName">"GRIPPER_LOWER__to__GRIPPER_CLOSE"</v>
                      <n n="EmbeddedTransition" />
                      <l2 n="EmbeddedTransitionProperties" />
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"state = States.GRIPPER_CLOSE"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">621L</v>
                          <v n="IdParent">620L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">622L</v>
                          <v n="IdParent">620L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">623L</v>
                          <v n="IdParent">620L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">624L</v>
                          <v n="IdParent">620L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">625L</v>
                          <v n="IdParent">620L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">626L</v>
                          <v n="IdParent">620L</v>
                        </o>
                      </l2>
                      <v n="Id">620L</v>
                      <v n="IdParent">9L</v>
                    </o>
                    <o t="SFCStep">
                      <n n="EmbeddedMainAction" />
                      <n n="EmbeddedEntryAction" />
                      <n n="EmbeddedExitAction" />
                      <l2 n="EmbeddedMainActionProperties" />
                      <l2 n="EmbeddedEntryActionProperties" />
                      <l2 n="EmbeddedExitActionProperties" />
                      <o n="ElementList" t="SFCElementList">
                        <l2 n="InnerList" />
                      </o>
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"GRIPPER_CLOSE"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">609L</v>
                          <v n="IdParent">608L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">610L</v>
                          <v n="IdParent">608L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">611L</v>
                          <v n="IdParent">608L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">612L</v>
                          <v n="IdParent">608L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">613L</v>
                          <v n="IdParent">608L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">614L</v>
                          <v n="IdParent">608L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">615L</v>
                          <v n="IdParent">608L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">616L</v>
                          <v n="IdParent">608L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"GRIPPER_CLOSE_active"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">617L</v>
                          <v n="IdParent">608L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">618L</v>
                          <v n="IdParent">608L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">619L</v>
                          <v n="IdParent">608L</v>
                        </o>
                      </l2>
                      <v n="Id">608L</v>
                      <v n="IdParent">9L</v>
                    </o>
                    <o t="SFCTransition">
                      <v n="VariableName">"GRIPPER_CLOSE__to__GRIPPER_LIFT"</v>
                      <n n="EmbeddedTransition" />
                      <l2 n="EmbeddedTransitionProperties" />
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"state = States.GRIPPER_LIFT"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">640L</v>
                          <v n="IdParent">639L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">641L</v>
                          <v n="IdParent">639L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">642L</v>
                          <v n="IdParent">639L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">643L</v>
                          <v n="IdParent">639L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">644L</v>
                          <v n="IdParent">639L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">645L</v>
                          <v n="IdParent">639L</v>
                        </o>
                      </l2>
                      <v n="Id">639L</v>
                      <v n="IdParent">9L</v>
                    </o>
                    <o t="SFCStep">
                      <n n="EmbeddedMainAction" />
                      <n n="EmbeddedEntryAction" />
                      <n n="EmbeddedExitAction" />
                      <l2 n="EmbeddedMainActionProperties" />
                      <l2 n="EmbeddedEntryActionProperties" />
                      <l2 n="EmbeddedExitActionProperties" />
                      <o n="ElementList" t="SFCElementList">
                        <l2 n="InnerList" />
                      </o>
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"GRIPPER_LIFT"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">628L</v>
                          <v n="IdParent">627L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">629L</v>
                          <v n="IdParent">627L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">630L</v>
                          <v n="IdParent">627L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">631L</v>
                          <v n="IdParent">627L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">632L</v>
                          <v n="IdParent">627L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">633L</v>
                          <v n="IdParent">627L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">634L</v>
                          <v n="IdParent">627L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">635L</v>
                          <v n="IdParent">627L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"GRIPPER_LIFT_active"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">636L</v>
                          <v n="IdParent">627L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">637L</v>
                          <v n="IdParent">627L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">638L</v>
                          <v n="IdParent">627L</v>
                        </o>
                      </l2>
                      <v n="Id">627L</v>
                      <v n="IdParent">9L</v>
                    </o>
                    <o t="SFCTransition">
                      <v n="VariableName">"GRIPPER_LIFT__to__LINEAR_BW"</v>
                      <n n="EmbeddedTransition" />
                      <l2 n="EmbeddedTransitionProperties" />
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"state = States.LINEAR_BW"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">521L</v>
                          <v n="IdParent">520L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">522L</v>
                          <v n="IdParent">520L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">523L</v>
                          <v n="IdParent">520L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">524L</v>
                          <v n="IdParent">520L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">525L</v>
                          <v n="IdParent">520L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">526L</v>
                          <v n="IdParent">520L</v>
                        </o>
                      </l2>
                      <v n="Id">520L</v>
                      <v n="IdParent">9L</v>
                    </o>
                    <o t="SFCStep">
                      <n n="EmbeddedMainAction" />
                      <n n="EmbeddedEntryAction" />
                      <n n="EmbeddedExitAction" />
                      <l2 n="EmbeddedMainActionProperties" />
                      <l2 n="EmbeddedEntryActionProperties" />
                      <l2 n="EmbeddedExitActionProperties" />
                      <o n="ElementList" t="SFCElementList">
                        <l2 n="InnerList" />
                      </o>
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"LINEAR_BW"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">509L</v>
                          <v n="IdParent">508L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">510L</v>
                          <v n="IdParent">508L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">511L</v>
                          <v n="IdParent">508L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">512L</v>
                          <v n="IdParent">508L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">513L</v>
                          <v n="IdParent">508L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">514L</v>
                          <v n="IdParent">508L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">515L</v>
                          <v n="IdParent">508L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">516L</v>
                          <v n="IdParent">508L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"LINEAR_BW_active"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">517L</v>
                          <v n="IdParent">508L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">518L</v>
                          <v n="IdParent">508L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">519L</v>
                          <v n="IdParent">508L</v>
                        </o>
                      </l2>
                      <v n="Id">508L</v>
                      <v n="IdParent">9L</v>
                    </o>
                    <o t="SFCTransition">
                      <v n="VariableName">"LINEAR_BW__to__GRIPPER_OPEN"</v>
                      <n n="EmbeddedTransition" />
                      <l2 n="EmbeddedTransitionProperties" />
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"state = States.GRIPPER_OPEN"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">676L</v>
                          <v n="IdParent">675L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">677L</v>
                          <v n="IdParent">675L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">678L</v>
                          <v n="IdParent">675L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">679L</v>
                          <v n="IdParent">675L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">680L</v>
                          <v n="IdParent">675L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">681L</v>
                          <v n="IdParent">675L</v>
                        </o>
                      </l2>
                      <v n="Id">675L</v>
                      <v n="IdParent">9L</v>
                    </o>
                    <o t="SFCStep">
                      <n n="EmbeddedMainAction" />
                      <n n="EmbeddedEntryAction" />
                      <n n="EmbeddedExitAction" />
                      <l2 n="EmbeddedMainActionProperties" />
                      <l2 n="EmbeddedEntryActionProperties" />
                      <l2 n="EmbeddedExitActionProperties" />
                      <o n="ElementList" t="SFCElementList">
                        <l2 n="InnerList" />
                      </o>
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"GRIPPER_OPEN"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">699L</v>
                          <v n="IdParent">698L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">700L</v>
                          <v n="IdParent">698L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">701L</v>
                          <v n="IdParent">698L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">702L</v>
                          <v n="IdParent">698L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">703L</v>
                          <v n="IdParent">698L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">704L</v>
                          <v n="IdParent">698L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">705L</v>
                          <v n="IdParent">698L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">706L</v>
                          <v n="IdParent">698L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"GRIPPER_OPEN_active"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">707L</v>
                          <v n="IdParent">698L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">708L</v>
                          <v n="IdParent">698L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">709L</v>
                          <v n="IdParent">698L</v>
                        </o>
                      </l2>
                      <v n="Id">698L</v>
                      <v n="IdParent">9L</v>
                    </o>
                    <o t="SFCTransition">
                      <v n="VariableName">"GRIPPER_OPEN__to__Init"</v>
                      <n n="EmbeddedTransition" />
                      <l2 n="EmbeddedTransitionProperties" />
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"state = States.ROTATE_DISC"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">468L</v>
                          <v n="IdParent">467L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">469L</v>
                          <v n="IdParent">467L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">470L</v>
                          <v n="IdParent">467L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">471L</v>
                          <v n="IdParent">467L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">472L</v>
                          <v n="IdParent">467L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">473L</v>
                          <v n="IdParent">467L</v>
                        </o>
                      </l2>
                      <v n="Id">467L</v>
                      <v n="IdParent">9L</v>
                    </o>
                    <o t="SFCJump">
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"Init"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">44L</v>
                          <v n="IdParent">43L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">45L</v>
                          <v n="IdParent">43L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">46L</v>
                          <v n="IdParent">43L</v>
                        </o>
                      </l2>
                      <v n="Id">43L</v>
                      <v n="IdParent">9L</v>
                    </o>
                  </l2>
                </o>
                <l2 n="Attributes" cet="SFCAttribute">
                  <o>
                    <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                    <o n="Value" t="StringValue">
                      <v n="Value">""</v>
                      <v n="DefaultValue">""</v>
                    </o>
                    <v n="Id">33L</v>
                    <v n="IdParent">9L</v>
                  </o>
                  <o>
                    <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                    <o n="Value" t="StringValue">
                      <v n="Value">""</v>
                      <v n="DefaultValue">""</v>
                    </o>
                    <v n="Id">34L</v>
                    <v n="IdParent">9L</v>
                  </o>
                  <o>
                    <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                    <o n="Value" t="BoolValue">
                      <v n="Value">"FALSE"</v>
                      <v n="DefaultValue">"FALSE"</v>
                    </o>
                    <v n="Id">35L</v>
                    <v n="IdParent">9L</v>
                  </o>
                </l2>
                <v n="Id">9L</v>
                <v n="IdParent">-1L</v>
              </o>
              <d2 n="Categories" ckt="Guid" cvt="SFCAttributeCategory">
                <v>1c5c6e05-2bb7-4258-bcee-fd16a540c63c</v>
                <o>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                  <v n="Identifier">"Specific"</v>
                  <v n="Parent">{00000000-0000-0000-0000-000000000000}</v>
                  <v n="Description">"Element type specific properties"</v>
                </o>
                <v>20f0fc67-978d-438b-979f-eef294f34ee4</v>
                <o>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{20f0fc67-978d-438b-979f-eef294f34ee4}</v>
                  <v n="Identifier">"Actions"</v>
                  <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                  <v n="Description">"Action definitions"</v>
                </o>
                <v>6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2</v>
                <o>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2}</v>
                  <v n="Identifier">"Common"</v>
                  <v n="Parent">{00000000-0000-0000-0000-000000000000}</v>
                  <v n="Description">"Common properties"</v>
                </o>
                <v>d336ba06-8a67-4e6b-9697-50f83ba6bdde</v>
                <o>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{d336ba06-8a67-4e6b-9697-50f83ba6bdde}</v>
                  <v n="Identifier">"Times"</v>
                  <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                  <v n="Description">"Time definitions"</v>
                </o>
              </d2>
              <d2 n="Attributes" ckt="Guid" cvt="SFCAttributeDescription">
                <v>01580b27-6378-448b-8ecb-0e4b795b58d6</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">true</v>
                  <v n="EditorVisibility">false</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                  <v n="Identifier">"Exclude"</v>
                  <v n="Parent">{6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2}</v>
                  <v n="Description">"Exclude this element from build"</v>
                </o>
                <v>23bdaa98-72ec-41f7-817b-9dede5697086</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">false</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{23bdaa98-72ec-41f7-817b-9dede5697086}</v>
                  <v n="Identifier">"Parallel"</v>
                  <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                  <v n="Description">"Sets the branch to parallel mode"</v>
                </o>
                <v>38391c6d-6d4a-42f8-8ee7-9f45e5adafa8</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">false</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                  <v n="Identifier">"Name"</v>
                  <v n="Parent">{6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2}</v>
                  <v n="Description">"Name of the element"</v>
                </o>
                <v>62e1754b-7629-4e63-9cec-10ae0c536f1f</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">false</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                  <v n="Identifier">"Duplication"</v>
                  <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                  <v n="Description">"Copies the implementation of step actions or transitions with the element. Otherwise, copies the reference to an existing implementation."</v>
                </o>
                <v>6844a48e-46c2-4cc8-a185-a478f3b99cc0</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">false</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                  <v n="Identifier">"InitStep"</v>
                  <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                  <v n="Description">"Sets the step as the initial step"</v>
                </o>
                <v>700a583f-b4d4-43e4-8c14-629c7cd3bec8</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">true</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                  <v n="Identifier">"MainAction"</v>
                  <v n="Parent">{20f0fc67-978d-438b-979f-eef294f34ee4}</v>
                  <v n="Description">"Name of the action to be called if the step is active"</v>
                </o>
                <v>7d894980-aeea-405c-a0f6-e2b26429c58f</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">true</v>
                  <v n="MultiLineEdit">true</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                  <v n="Identifier">"Comment"</v>
                  <v n="Parent">{6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2}</v>
                  <v n="Description">"Comment of the element"</v>
                </o>
                <v>8294df19-5962-4dee-a874-1051dabb0e3e</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">false</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                  <v n="Identifier">"Monitoring"</v>
                  <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                  <v n="Description">"Indicates transition monitoring setting."</v>
                </o>
                <v>a2621e18-7de3-4ea6-ae6d-89e9e0b7befd</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">true</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                  <v n="Identifier">"ExitAction"</v>
                  <v n="Parent">{20f0fc67-978d-438b-979f-eef294f34ee4}</v>
                  <v n="Description">"Name of the action to be called if the step is deactivated"</v>
                </o>
                <v>a6b08bd8-b696-47e3-9cbf-7408b61c9ff8</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">true</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                  <v n="Identifier">"EntryAction"</v>
                  <v n="Parent">{20f0fc67-978d-438b-979f-eef294f34ee4}</v>
                  <v n="Description">"Name of the action to be called if the step is activated"</v>
                </o>
                <v>b693554c-1b01-4a8d-afde-9e3a46f7465d</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">true</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                  <v n="Identifier">"MaxTime"</v>
                  <v n="Parent">{d336ba06-8a67-4e6b-9697-50f83ba6bdde}</v>
                  <v n="Description">"Defines the maximal active time for the step"</v>
                </o>
                <v>bc882c11-1e91-4dd8-a6b8-2075724ed18b</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">true</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                  <v n="Identifier">"Symbol"</v>
                  <v n="Parent">{6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2}</v>
                  <v n="Description">"Symbol configuration setting of the element"</v>
                </o>
                <v>cacf1a68-236e-47c2-b7b1-1cf9199718cb</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">true</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                  <v n="Identifier">"MinTime"</v>
                  <v n="Parent">{d336ba06-8a67-4e6b-9697-50f83ba6bdde}</v>
                  <v n="Description">"Defines the minimal active time for the step"</v>
                </o>
                <v>e174fc0d-80b0-4a9e-a530-ca239c249a50</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">false</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{e174fc0d-80b0-4a9e-a530-ca239c249a50}</v>
                  <v n="Identifier">"Qualifier"</v>
                  <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                  <v n="Description">"Qualifier of the action association"</v>
                </o>
              </d2>
              <d2 n="EnumTemplates" ckt="Guid" cvt="EnumValueTemplate">
                <v>6ecff51c-9b8f-4338-aab0-67c2b31b07e9</v>
                <o>
                  <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                  <l n="Values" t="ArrayList" cet="EnumEntry">
                    <o>
                      <v n="Identifier">"None"</v>
                      <v n="Value">0L</v>
                      <v n="Key">"None"</v>
                    </o>
                    <o>
                      <v n="Identifier">"Variable"</v>
                      <v n="Value">1L</v>
                      <v n="Key">"Variable"</v>
                    </o>
                    <o>
                      <v n="Identifier">"Call"</v>
                      <v n="Value">2L</v>
                      <v n="Key">"Call"</v>
                    </o>
                  </l>
                  <v n="BaseType">"INT"</v>
                </o>
                <v>79a4fdd5-c859-4de4-aa8d-c03372c880c2</v>
                <o>
                  <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                  <l n="Values" t="ArrayList" cet="EnumEntry">
                    <o>
                      <v n="Identifier">"Unspecified"</v>
                      <v n="Value">0L</v>
                      <v n="Key">"Unspecified"</v>
                    </o>
                    <o>
                      <v n="Identifier">"None"</v>
                      <v n="Value">1L</v>
                      <v n="Key">"None"</v>
                    </o>
                    <o>
                      <v n="Identifier">"Read"</v>
                      <v n="Value">2L</v>
                      <v n="Key">"Read"</v>
                    </o>
                    <o>
                      <v n="Identifier">"Write"</v>
                      <v n="Value">3L</v>
                      <v n="Key">"Write"</v>
                    </o>
                    <o>
                      <v n="Identifier">"ReadWrite"</v>
                      <v n="Value">4L</v>
                      <v n="Key">"ReadWrite"</v>
                    </o>
                  </l>
                  <v n="BaseType">"INT"</v>
                </o>
              </d2>
            </o>
          </Data>
          <TypeList>
            <Type n="ArrayList">System.Collections.ArrayList</Type>
            <Type n="Boolean">System.Boolean</Type>
            <Type n="BoolValue">{89e1c7bb-c9f8-4be3-b8a7-019cdbb9f7e8}</Type>
            <Type n="EnumEntry">{4185e6da-1717-44c9-b705-102861764479}</Type>
            <Type n="EnumValue">{4dd7572b-4b9d-4d35-963e-6a34a4aaa5c1}</Type>
            <Type n="EnumValueTemplate">{d6bfe4f0-d62f-4b5f-9f95-2bbeb1950e28}</Type>
            <Type n="Guid">System.Guid</Type>
            <Type n="Int64">System.Int64</Type>
            <Type n="SFCAttribute">{21f3f16e-04fa-4637-b6b7-d84e4192e99f}</Type>
            <Type n="SFCAttributeCategory">{679adacf-f2a4-4167-a3f7-d21cfc5d451f}</Type>
            <Type n="SFCAttributeDescription">{d851789d-af2c-4990-9d48-a7bdc9181773}</Type>
            <Type n="SFCElementList">{587d6556-cfe6-4e76-9cc9-fc0daf0c8c29}</Type>
            <Type n="SFCImplementationObject">{74f81948-1328-492c-b6c1-a9ea72048b28}</Type>
            <Type n="SFCJump">{7e39ac27-154f-419a-a255-6a6cf37d5ed0}</Type>
            <Type n="SFCSegment">{f1db7f6f-4774-46a6-ad9b-a94414f875fc}</Type>
            <Type n="SFCStep">{86ee92a2-d863-4136-be27-82b36d84211c}</Type>
            <Type n="SFCTransition">{4ecb29e8-a90a-4646-84ac-2ff54215ab29}</Type>
            <Type n="String">System.String</Type>
            <Type n="StringValue">{778c8bac-3fa0-41e1-99d3-2b628d12d3e5}</Type>
          </TypeList>
        </XmlArchive>
      </SFC>
    </Implementation>
    <Action Name="GRIPPER_CLOSE_active" Id="{d691e21a-f8c1-4a63-8118-7801ba5c32fe}">
      <Implementation>
        <ST><![CDATA[Timer.GripperClose(IN:=TRUE, PT:=GVL.GRIPPER_CLOSE_TIME);

OutputSignals.Gripper := FALSE;

IF Timer.GripperClose.Q THEN
	state := States.GRIPPER_LIFT;
END_IF]]></ST>
      </Implementation>
    </Action>
    <Action Name="GRIPPER_LIFT_active" Id="{4cd9cfc3-9895-41ad-abcb-f725e0d1d34a}">
      <Implementation>
        <ST><![CDATA[Timer.GripperLift(IN:=TRUE, PT:=GVL.GRIPPER_LIFT_TIME);

OutputSignals.GripperMotor := BOOL_TO_INT(NOT Timer.GripperLift.Q);

IF Timer.GripperLift.Q THEN
	CylinderInDisc[1] := FALSE;
	TotalNumberCylindersPicked := TotalNumberCylindersPicked + 1;
	state := States.LINEAR_BW;
END_IF]]></ST>
      </Implementation>
    </Action>
    <Action Name="GRIPPER_LOWER_active" Id="{12b64b9a-ca2e-4622-9620-65a67211656e}">
      <Implementation>
        <ST><![CDATA[Timer.GripperLower(IN:=TRUE, PT:=GVL.GRIPPER_LOWER_TIME);

OutputSignals.GripperMotor := - BOOL_TO_INT(NOT Timer.GripperLower.Q);

IF Timer.GripperLower.Q THEN
	state := States.GRIPPER_CLOSE;
END_IF]]></ST>
      </Implementation>
    </Action>
    <Action Name="GRIPPER_OPEN_active" Id="{12264ac5-96a8-41b7-aa00-1dd1bd9e69e7}">
      <Implementation>
        <ST><![CDATA[Timer.GripperOpen(IN:=TRUE, PT:=GVL.GRIPPER_OPEN_TIME);

OutputSignals.Gripper := TRUE;

IF Timer.GripperOpen.Q THEN
	state := States.ROTATE_DISC;
END_IF]]></ST>
      </Implementation>
    </Action>
    <Action Name="Init_entry" Id="{f8394b6a-6890-42bc-b48d-484abeb66bcb}">
      <Implementation>
        <ST><![CDATA[Sensor := CylinderInDisc[4];

Timer.RotateDisc(IN:=FALSE);
Timer.LinearFW(IN:=FALSE);
Timer.GripperLower(IN:=FALSE);
Timer.GripperOpen(IN:=FALSE);
Timer.GripperClose(IN:=FALSE);
Timer.GripperLift(IN:=FALSE);
Timer.LinearBW(IN:=FALSE);

//CyclesCounter := TotalCyclesCounter MOD GVL.NUMBER_OF_SLOTS;]]></ST>
      </Implementation>
    </Action>
    <Action Name="LINEAR_BW_active" Id="{04b344ae-3198-4f12-b7a5-389db0f028f0}">
      <Implementation>
        <ST><![CDATA[Timer.LinearBW(IN:=TRUE, PT:=GVL.LINEAR_FW_TIME);

OutputSignals.Motor1 := - BOOL_TO_INT(NOT Timer.LinearBW.Q);

IF Timer.LinearBW.Q THEN
	state := States.GRIPPER_OPEN;
END_IF]]></ST>
      </Implementation>
    </Action>
    <Action Name="LINEAR_FW_active" Id="{c6f886f3-66c7-48bf-a531-e24bbdd03a9a}">
      <Implementation>
        <ST><![CDATA[Timer.LinearFW(IN:=TRUE, PT:=GVL.LINEAR_FW_TIME);

OutputSignals.Motor1 := BOOL_TO_INT(NOT Timer.LinearFW.Q);

IF Timer.LinearFW.Q THEN
	state := States.GRIPPER_LOWER;
END_IF]]></ST>
      </Implementation>
    </Action>
    <Action Name="ROTATE_DISC_active" Id="{0c13a474-856b-411f-9f0d-bd90afbbad44}">
      <Implementation>
        <ST><![CDATA[Timer.RotateDisc(IN:=TRUE, PT:=GVL.ROTATE_DISC_TIME);

OutputSignals.Motor2 := BOOL_TO_INT(NOT Timer.RotateDisc.Q);

IF Timer.RotateDisc.Q THEN
	Timer.RotateDisc(IN:=FALSE);
	FOR i:=1 TO 5 BY 1 DO
		CylinderInDisc[i] := CylinderInDisc[i+1];
	END_FOR;
	CylinderInDisc[6] := PutCylinderInSlot6;
	IF CylinderInDisc[1] THEN
		state := States.LINEAR_FW;
	END_IF	
END_IF]]></ST>
      </Implementation>
    </Action>
    <ObjectProperties>
      <XmlArchive>
        <Data>
          <o xml:space="preserve" t="SFCProperty">
            <n n="SFCErrorAnalyzation" />
            <n n="SFCErrorAnalyzationTable" />
            <v n="Title">"IecSfc"</v>
            <v n="Company">"System"</v>
            <v n="Version">"3.4.2.0"</v>
            <v n="Namespace">""</v>
            <d2 n="Flags" ckt="Flags" cvt="SFCPropertyFlagData">
              <v>EnableLimit</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>Init</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>Reset</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>QuitError</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>Pause</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>Error</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>Trans</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>ErrorStep</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>ErrorPOU</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>CurrentStep</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>Tip</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>TipMode</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>SFCErrorAnalyzation</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>SFCErrorAnalyzationTable</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
            </d2>
            <v n="CalcActiveTransOnly">false</v>
            <v n="UseDefaults">true</v>
          </o>
        </Data>
        <TypeList>
          <Type n="Boolean">System.Boolean</Type>
          <Type n="Flags">{27d8150b-ef58-4fff-8da1-1f7dd5f9ea51}</Type>
          <Type n="SFCProperty">{58548d2c-f1b1-453d-9195-66c94e2a3ae0}</Type>
          <Type n="SFCPropertyFlagData">{24565a38-6368-4874-ab9a-0ef7ec269521}</Type>
          <Type n="String">System.String</Type>
        </TypeList>
      </XmlArchive>
    </ObjectProperties>
    <LineIds Name="StateMachine.GRIPPER_CLOSE_active">
      <LineId Id="2" Count="5" />
      <LineId Id="1" Count="0" />
    </LineIds>
    <LineIds Name="StateMachine.GRIPPER_LIFT_active">
      <LineId Id="2" Count="5" />
      <LineId Id="9" Count="0" />
      <LineId Id="8" Count="0" />
      <LineId Id="1" Count="0" />
    </LineIds>
    <LineIds Name="StateMachine.GRIPPER_LOWER_active">
      <LineId Id="2" Count="5" />
      <LineId Id="1" Count="0" />
    </LineIds>
    <LineIds Name="StateMachine.GRIPPER_OPEN_active">
      <LineId Id="2" Count="5" />
      <LineId Id="1" Count="0" />
    </LineIds>
    <LineIds Name="StateMachine.Init_entry">
      <LineId Id="2" Count="8" />
      <LineId Id="13" Count="0" />
      <LineId Id="12" Count="0" />
    </LineIds>
    <LineIds Name="StateMachine.LINEAR_BW_active">
      <LineId Id="2" Count="5" />
      <LineId Id="1" Count="0" />
    </LineIds>
    <LineIds Name="StateMachine.LINEAR_FW_active">
      <LineId Id="2" Count="5" />
      <LineId Id="1" Count="0" />
    </LineIds>
    <LineIds Name="StateMachine.ROTATE_DISC_active">
      <LineId Id="2" Count="12" />
      <LineId Id="1" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>